name: Cypress tests

on:
  push:
    branches: main

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      
      - name: Cypress run
        uses: cypress-io/github-action@v6